"""
Django settings for BooksRenter project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tu=(5hrp2r(licr0mo$r2%^aoc1mlj7n%lx2930*1d_7dmr@tz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',
    # 'accounts',
    'books',
    'invoice',
    'user',
    'users',
    'phonenumber_field',
    'suppliers',
    'orders',
    'transactions',
    'cart',
    'celery', 
    'upload',  
    'rest_framework',
    'rest_framework_swagger',
    'django_filters',
    'paytm',
    'payment',
    'payu',
    'paypal.standard.ipn',
    'scrapper',
    'manufacturer',
    'Home',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BooksRenter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'BooksRenter.wsgi.application'


CELERY_BROKER_URL = 'amqp://localhost'


# EMAIL_BACKEND = 'django_mailgun.MailgunBackend'
# MAILGUN_ACCESS_KEY = '7b28b6019e154eb498e2aa50d80f2f54-52cbfb43-5366cb50'
# MAILGUN_SERVER_NAME = 'https://api.mailgun.net/v3/sandbox8968d33240a44a97891ddf437f80e3ad.mailgun.org'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_HOST_USER='collexatech@nvn.com'
# EMAIL_HOST_PASSWORD= 'mailgun123'
# EMAIL_PORT = 587

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_HOST_USER = 'manjucollexa@gmail.com'
# EMAIL_HOST_PASSWORD = 'collexa1234567'
# EMAIL_PORT = 587


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'http://127.0.0.1:8000'
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'mybook_database',
        'USER': 'myuser',
        'PASSWORD': 'mybook',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/






import datetime



REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
    'COERCE_DECIMAL_TO_STRING': False,
}

JWT_AUTH = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=1),
    'JWT_ALLOW_REFRESH': False,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_AUTH_HEADER_PREFIX': 'token',
}

PHONENUMBER_DEFAULT_REGION = 'IND'



AUTH_USER_MODEL = 'users.User'


CART_SESSION_ID = 'cart'

#django-paypal 
PAYPAL_RECEIVER_EMAIL = 'wadbudenvn19.test1@gmail.com'
PAYPAL_TEST = True


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = '/media/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'


PHONENUMBER_DEFAULT_REGION = 'IND'


PAYTM_MERCHANT_KEY = "<AkaTNBbzEXLy_Mpk>"
PAYTM_MERCHANT_ID = "<collex63784704295825>"
HOST_URL = "http://127.0.0.1:8080"
PAYTM_CALLBACK_URL = "/paytm/response/"
if DEBUG:
    PAYTM_MERCHANT_KEY = "AkaTNBbzEXLy_Mpk"
    PAYTM_MERCHANT_ID = "collex63784704295825"
    PAYTM_WEBSITE = 'WEB_STAGING'
    HOST_URL = 'http://127.0.0.1:8000'


CASHFREE_APPID = '297634f5b80918871d0f15946792'
CASHFREE_SECRETKEY = '94fde338ac4fb7f254b2578d70c02078901cec95'
CASHFREE_MODE = ''
CASHFREE_SUCCESS_URL = '/'
CASHFREE_FAILURE_URL = '/'
CASHFREE_PAYMENT_BY_URL = False


####### Pay yu payment integration information###################
PAYU_MERCHANT_KEY = "ikaSBIxj" # Merchant key from payu
PAYU_KEY = "ikaSBIxj"
PAYU_SALT = "L8o3RR3d6B" # Merchant salt from payu
PAYMENT_MODE ='TEST'
PAYU_SUCCESS_URL = 'http://127.0.0.1:8000/payment/success/' # success url
PAYU_FAILURE_URL = 'http://127.0.0.1:8000/payment/failure/' # failure url

# PAID_FEE_AMOUNT = 1
# PAID_FEE_PRODUCT_INFO = "Message showing product details."
# PAYMENT_URL_TEST = 'https://test.payu.in/_payment'
# PAYMENT_URL_LIVE = 'https://secure.payu.in/_payment'
# SERVICE_PROVIDER = "payu_paisa"

SALT = 'L8o3RR3d6B'
MERCHANT_KEY = 'ikaSBIxj'